#!/bin/bash

# REFERENCE:
# https://github.com/akiym/WWW-FC2Video-Download

CMD=`basename $0`

show_help()
{
    echo "Usage: $CMD <URL> [FORCE={0/1}]"
}

find_unique_filename()
{
    if [ $# -ne 2 ]; then
        echo "Fail! -- Expecting 2 arguments! ==> $@"
        return 1 # non-zero as false
    fi
    local UNIQUE_FILENAME_VAR=$1
    local FILENAME=$2
    if [ -f $FILENAME ]; then
        COUNTER=0
        while [ -f $FILENAME ]; do
            echo "File exists: `basename $FILENAME`"
            local NEW_FILENAME=`echo $FILENAME | sed "s#\(.*\)-[0-9]\+\.#\1-$COUNTER\.#g"`
            if [ "$NEW_FILENAME" == "$FILENAME" ]; then
                NEW_FILENAME=`echo $FILENAME | sed "s#\(.*\)\.#\1-$COUNTER\.#g"`
            fi
            FILENAME=$NEW_FILENAME
            COUNTER=$(( $COUNTER + 1 ))
        done
        echo "Next unique filename: `basename $FILENAME`"
    fi
    eval "$UNIQUE_FILENAME_VAR=$FILENAME"
}

if [ $# -ne 1 -a $# -ne 2 ]; then
    echo "Fail! -- Expecting 1 or 2 arguments! ==> $@"
    show_help
    exit 1
fi

if [ ! -f "`pwd`/fc2-dl-core.pl" ]; then
    echo "Fail! -- Requires Perl script \"`pwd`/fc2-dl-core.pl\""
    echo "Hint: git clone https://github.com/otheralias/fc2-dl.git"
    exit 1
fi

if [ ! -d "`pwd`/WWW-FC2Video-Download" ]; then
    echo "Fail! -- Requires Perl module \"WWW::FC2Video::Download\""
    echo "Hint: git clone https://github.com/akiym/WWW-FC2Video-Download.git"
    exit 1
fi

URL=$1
FORCE=$2

if [ -z "$FORCE" ]; then
    FORCE=0
fi

echo ""
echo "Extracting video UPID from.. ==> $URL"
UPID=`curl $URL                   | # download HTML using curl
        tr -d '\n'                | # remove carriage returns
        sed 's#</#\n</#g'         | # tokenize by HTML tag
        grep 'kobj_up_id='        | # locate lines with "kobj_up_id="
        tr '\n' @                 | # tokenize by line
        cut -d@ -f1               | # isolate first instance
        sed 's/^.*kobj_up_id=//g' | # remove everything before "kobj_up_id="
        sed 's/&.*$//g'`            # remove everything after "&"

if [ -z "$UPID" ]; then
    echo ""
    echo "Fail! -- UPID not found!"
    exit 1
fi

echo ""
echo "Found UPID=\"$UPID\""
LOCAL_FILE=`perl -I WWW-FC2Video-Download/lib fc2-dl-core.pl "$UPID" 1`
LOCAL_FILE=`echo $LOCAL_FILE | sed "s/ /_/g"`
if [ $FORCE -eq 1 ] && [ -f $LOCAL_FILE ]; then
    echo "Overwriting.. ==> `basename $LOCAL_FILE`"
else
    if find_unique_filename LOCAL_FILE $LOCAL_FILE; then
        : # do nothing
    else
        exit 1
    fi
    echo "Saving as new.. ==> `basename $LOCAL_FILE`"
fi
touch $LOCAL_FILE
TEMP=${LOCAL_FILE}.part
trap "rm -f $TEMP" EXIT
perl -I WWW-FC2Video-Download/lib fc2-dl-core.pl "$UPID" 2 $TEMP
mv $TEMP $LOCAL_FILE

echo ""
echo "Download complete! ==> $LOCAL_FILE"
