#!/bin/bash

# REFERENCE:
# https://github.com/akiym/WWW-FC2Video-Download

CMD=`basename $0`

show_help()
{
    echo "Usage: $CMD <URL>"
}

if [ $# -ne 1 ]; then
    echo "fail! -- expect 1 arguments! ==> $@"
    show_help
    exit 1
fi

if [ ! -d "`pwd`/WWW-FC2Video-Download" ]; then
    echo "fail! -- requires Perl module \"WWW::FC2Video::Download\""
    echo "hint: git clone https://github.com/akiym/WWW-FC2Video-Download.git"
    exit 1
fi

if [ ! -f "`pwd`/fc2-dl-core.pl" ]; then
    echo "fail! -- requires Perl script \"`pwd`/fc2-dl-core.pl\""
    echo "hint: git clone https://github.com/otheralias/fc2-dl.git"
    exit 1
fi

URL=$1

echo ""
echo "Extracting video UPID from.. ==> $URL"
UPID=`curl $URL                   | # download HTML using curl
        tr -d '\n'                | # remove carriage returns
        sed 's#</#\n</#g'         | # tokenize by HTML tag
        grep 'kobj_up_id='        | # locate lines with "kobj_up_id="
        tr '\n' @                 | # tokenize by line
        cut -d@ -f1               | # isolate first instance
        sed 's/^.*kobj_up_id=//g' | # remove everything before "kobj_up_id="
        sed 's/&.*$//g'`            # remove everything after "&"

if [ -n "$UPID" ]; then
    echo ""
    echo "Found UPID=\"$UPID\""
    perl -I WWW-FC2Video-Download/lib fc2-dl-core.pl "$UPID"
fi
